apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-video-chaptering-config
  namespace: ai-video-chaptering
data:
  # Flask Configuration
  FLASK_ENV: "production"
  
  # CORS Configuration
  CORS_ORIGINS: "https://ai-video-chaptering.skafldstudio.com"
  
  # File Storage Paths
  MODEL_CACHE_DIR: "/app/models"
  UPLOAD_FOLDER: "/app/storage/uploads"
  PROCESSED_FOLDER: "/app/storage/processed"
  MAX_CONTENT_LENGTH: "500MB"
  
  # AI Model Configuration
  WHISPER_MODEL: "base"
  LLM_MODEL: "microsoft/DialoGPT-medium"
  USE_GPU: "false"
  DEVICE: "cpu"
  
  # DigitalOcean Spaces Configuration
  DO_SPACES_REGION: "sfo3"
  
  # WebSocket Configuration
  SOCKETIO_ASYNC_MODE: "eventlet"
  SOCKETIO_CORS_ALLOWED_ORIGINS: "*"
  
  # Logging and Monitoring
  LOG_LEVEL: "INFO"
  LOG_FILE: "/app/logs/app.log"
  
  # Security
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_DEFAULT: "200 per day, 50 per hour"
  
  # Frontend Configuration
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1" 