apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-video-chaptering

resources:
- namespace.yaml
- configmap.yaml
- secrets.yaml
- persistent-volumes.yaml
- backend-deployment.yaml
- celery-worker-deployment.yaml
- celery-flower-deployment.yaml
- frontend-deployment.yaml
- ingress.yaml
- database-init-job.yaml

commonLabels:
  app: ai-video-chaptering
  version: v1.0.0

images:
- name: registry.digitalocean.com/skafldstudio/ai-video-chaptering-backend
  newTag: latest
- name: registry.digitalocean.com/skafldstudio/ai-video-chaptering-frontend
  newTag: latest

replicas:
- name: backend-api
  count: 2
- name: celery-worker
  count: 2
- name: frontend
  count: 3
- name: celery-flower
  count: 1

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: backend-api
    namespace: ai-video-chaptering
  spec:
    template:
      spec:
        containers:
        - name: backend-api
          env:
          - name: CLUSTER_NAME
            value: "skafldstudio-remotedev" 