apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-models-storage
  namespace: ai-video-chaptering
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: do-block-storage-retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-logs-storage
  namespace: ai-video-chaptering
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage-retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: temp-storage
  namespace: ai-video-chaptering
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: do-block-storage-retain 