apiVersion: v1
kind: Secret
metadata:
  name: ai-video-chaptering-secrets
  namespace: ai-video-chaptering
type: Opaque
stringData:
  # Flask Configuration
  SECRET_KEY: "your-flask-secret-key-here"
  
  # Database Configuration
  DATABASE_URL: "postgresql://username:password@your-postgres-host:5432/dbname"
  REDIS_URL: "redis://username:password@your-redis-host:6379"
  
  # Celery Configuration
  CELERY_BROKER_URL: "redis://username:password@your-redis-host:6379/1"
  CELERY_RESULT_BACKEND: "redis://username:password@your-redis-host:6379/2"
  
  # DigitalOcean Spaces Configuration
  DO_SPACES_ENDPOINT: "https://your-bucket.region.digitaloceanspaces.com"
  DO_SPACES_BUCKET: "your-bucket-name"
  DO_SPACES_ACCESS_KEY: "your-spaces-access-key"
  DO_SPACES_SECRET_KEY: "your-spaces-secret-key"
  
  # Flower Monitoring
  FLOWER_USER: "admin"
  FLOWER_PASSWORD: "secure-flower-password"
  
  # Monitoring
  SENTRY_DSN: "your-sentry-dsn-here"
  
  # Frontend Configuration
  NEXT_PUBLIC_API_URL: "https://api.your-domain.com"
  NEXT_PUBLIC_WS_URL: "wss://api.your-domain.com"
