apiVersion: v1
kind: Secret
metadata:
  name: ai-video-chaptering-secrets
  namespace: ai-video-chaptering
type: Opaque
stringData:
  # Flask Configuration - Generate with: python -c "import secrets; print(secrets.token_urlsafe(32))"
  SECRET_KEY: "CHANGE_ME_TO_RANDOM_SECRET_KEY"
  
  # Database Configuration - These will be your actual database URLs
  DATABASE_URL: "postgresql://doadmin:password@db-postgresql-sfo3-xxxxx.db.ondigitalocean.com:25060/defaultdb?sslmode=require"
  REDIS_URL: "rediss://default:password@db-redis-sfo3-xxxxx.db.ondigitalocean.com:25061"
  
  # Celery Configuration - Same Redis URL with different databases
  CELERY_BROKER_URL: "rediss://default:password@db-redis-sfo3-xxxxx.db.ondigitalocean.com:25061/1"
  CELERY_RESULT_BACKEND: "rediss://default:password@db-redis-sfo3-xxxxx.db.ondigitalocean.com:25061/2"
  
  # DigitalOcean Spaces Configuration
  DO_SPACES_ENDPOINT: "https://sfo3.digitaloceanspaces.com"
  DO_SPACES_BUCKET: "ai-video-chaptering"
  DO_SPACES_ACCESS_KEY: "YOUR_SPACES_ACCESS_KEY"
  DO_SPACES_SECRET_KEY: "YOUR_SPACES_SECRET_KEY"
  
  # Flower Monitoring - Generate secure password
  FLOWER_USER: "admin"
  FLOWER_PASSWORD: "CHANGE_ME_TO_SECURE_PASSWORD"
  
  # Monitoring (Optional)
  SENTRY_DSN: ""
  
  # Frontend Configuration - Update with your actual domain
  NEXT_PUBLIC_API_URL: "https://api.yourdomain.com"
  NEXT_PUBLIC_WS_URL: "wss://api.yourdomain.com"